project:
  type: book
  output-dir: docs

book:
  title: "Real Analysis Dialogues"
  author: Renu Dhadwal
  chapters:
    - index.qmd
    - chapters/Completeness.qmd

format:
  html:
    theme: cosmo
    css: styles/course.css

execute:
  enabled: false
