project:
  type: book
  output-dir: docs

book:
  title: "Fractional Calculus Adventure"
  author: Renu Dhadwal
  chapters:
    - index.qmd
    - chapters/level1_temple_of_smriti.qmd
    - chapters/level2_river_of_derivatives.qmd
    - chapters/level2_5_grove_of_expansions.qmd

format:
  html:
    theme: cosmo
    css: styles/course.css

execute:
  enabled: false
